# Generated by Django 3.1.2 on 2020-11-19 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bookreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreport',
            name='parent',
        ),
    ]
